"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "pt" | "en" | "ru" | "et"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  pt: {
    welcome: "Bem-vindo ao meu portfolio",
    about: "Sobre Mim",
    skills: "Minhas Habilidades",
    seeAllRepos: "Ver todos os repositórios",
    projects: "Projetos Recentes",
    exp1Title: "Engenheiro de Software Sênior",
    exp1Company: "Riverty",
    exp1CompanyUrl: "https://riverty.com",
    exp1Location: "Tallinn, Estônia",
    exp1Period: "2022 - Presente",
    exp1Description: "Desenvolvimento de aplicações web com React e Next.js. Implementação de design systems e otimização de performance.",
    exp2Title: "Engenheiro de Software",
    exp2Company: "Arvato Financial Solutions Tech Center",
    exp2CompanyUrl: "https://arvato.com",
    exp2Location: "Tallinn, Estônia",
    exp2Period: "2022 - 2022",
    exp2Description: "Desenvolvimento de aplicações web com React e Next.js. Implementação de design systems e otimização de performance.",
    exp3Title: "Desenvolvedor Full Stack",
    exp3Company: "MAGIT IT PARTNER",
    exp3Location: "Ribeirão Preto, Brasil",
    exp3Period: "2020 - 2022",
    exp3Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp4Title: "Desenvolvedor Full Stack",
    exp4Company: "GooWe",
    exp4Location: "Ribeirão Preto, Brasil",
    exp4Period: "2019 - 2020",
    exp4Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp5Title: "Desenvolvedor Full Stack",
    exp5Company: "Kezz IT",
    exp5Location: "Ribeirão Preto, Brasil",
    exp5Period: "2019 - 2019",
    exp5Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp6Title: "Desenvolvedor Full Stack",
    exp6Company: "Onsoft Web",
    exp6Location: "Ribeirão Preto, Brasil",
    exp6Period: "2018 - 2019",
    exp6Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    exp7Title: "Web Freelancer",
    exp7Company: "Freelance",
    exp7Location: "Ribeirão Preto, Brasil",
    exp7Period: "2018 - 2019",
    exp7Description: "Desenvolvimento de sites responsivos e landing pages para clientes de diversos setores.",
    skillCSharpName: "C#",
    skillCSharpCategory: "Linguagens",
    skillCSharpDescription: "Arquitetura de sistemas financeiros críticos com .NET Core, microserviços escaláveis e integração com Kafka. +7 anos desenvolvendo APIs robustas para processamento de alto volume.",
    skillGoName: "Go",
    skillGoCategory: "Linguagens",
    skillGoDescription: "Criação de ferramentas CLI robustas e microserviços de alta performance. Autor do GCLI com 32 stars, especialista em concorrência e sistemas distribuídos.",
    skillTypeScriptName: "TypeScript",
    skillTypeScriptCategory: "Linguagens",
    skillTypeScriptDescription: "Desenvolvimento de Web Components enterprise com Stencil.js em ambiente financeiro. Especialista em aplicações full-stack type-safe e arquitetura escalável.",
    skillAngularName: "Angular",
    skillAngularCategory: "Frontend",
    skillAngularDescription: "Desenvolvimento de SPAs complexas e sistemas de design. Integração com Web Components e state management avançado para aplicações enterprise.",
    skillIonicName: "Ionic",
    skillIonicCategory: "Mobile",
    skillIonicDescription: "Desenvolvimento de aplicações híbridas cross-platform com Angular e Capacitor. Experiência em publicação e otimização para iOS e Android.",
    skillSwiftUIName: "SwiftUI",
    skillSwiftUICategory: "Mobile",
    skillSwiftUIDescription: "Desenvolvimento nativo iOS com SwiftUI e Combine. Atualmente dedicando 59% do tempo de desenvolvimento em projetos Swift, criando interfaces modernas e performáticas.",
    skillStencilJSName: "StencilJS",
    skillStencilJSCategory: "Frontend",
    skillStencilJSDescription: "Web Components para sistemas financeiros enterprise na Riverty. Criação de design systems reutilizáveis e componentes de alta performance para aplicações críticas.",
    skillMongoDBName: "MongoDB",
    skillMongoDBCategory: "Banco de Dados",
    skillMongoDBDescription: "Modelagem de dados NoSQL para sistemas de alto volume. Otimização de queries e implementação de estratégias de sharding para aplicações financeiras escaláveis.",
    skillSQLServerName: "SQLServer",
    skillSQLServerCategory: "Banco de Dados",
    skillSQLServerDescription: "Administração de bancos SQL, otimização de queries e procedures.",
    skillOracleName: "Oracle",
    skillOracleCategory: "Banco de Dados",
    skillOracleDescription: "Gerenciamento de grandes volumes de dados e PL/SQL para automação.",
    skillDockerName: "Docker",
    skillDockerCategory: "DevOps",
    skillDockerDescription: "Containerização de microserviços e orquestração de ambientes complexos. Implementação de CI/CD pipelines e gestão de infraestrutura para aplicações financeiras.",
    skillKubernetesName: "Kubernetes",
    skillKubernetesCategory: "DevOps",
    skillKubernetesDescription: "Orquestração de contêineres, autoescalabilidade e deploys resilientes.",
    skillBicepName: "Bicep",
    skillBicepCategory: "DevOps",
    skillBicepDescription: "Infraestrutura como código para deployments Azure em produção. Automação de provisionamento de recursos e gestão de ambientes para aplicações enterprise.",
    skillTerraformName: "Terraform",
    skillTerraformCategory: "DevOps",
    skillTerraformDescription: "Automação de infraestrutura multi-cloud e gerenciamento de estado.",
    projectUrlShortenerTitle: "URL-Shortener",
    projectUrlShortenerDescription: "Plataforma para encurtar URLS sendo capaz de suportar um grade volume de dados, tendo sido feito deploy na Azure.",
    projectUrlShortenerFeature1: "Geração de URLs curtas",
    projectUrlShortenerFeature2: "Redirecionamento de URLs",
    projectUrlShortenerFeature3: "Estatísticas de acesso",
    projectUrlShortenerFeature4: "Observabilidade",
    projectGcliTitle: "GCLI",
    projectGcliDescription: "CLI em Golang para criação de projetos projetos em Golang, ja contendo uma estrutura robusta e pronta para producao.",
    projectGcliFeature1: "Criação de projetos em Golang com multiplos templates",
    projectGcliFeature2: "Geração de CRUDs de formas simplificadas",
    projectGcliFeature3: "Servidor de Migration com Hot Reload",
    projectGcliFeature4: "Dockerização do projeto",
    projectGcliFeature5: "Pronto para produção",
    projectMtgCardInventoryTitle: "MTG Card Inventory",
    projectMtgCardInventoryDescription: "Aplicativo para gerenciamento de inventário e decks de cartas de Magic The Gathering.",
    projectMtgCardInventoryFeature1: "Listagem de cartas catalogadas com filtros avançados",
    projectMtgCardInventoryFeature2: "Criação de decks personalizados",
    projectMtgCardInventoryFeature3: "Sincronização com banco de dados remoto",
    projectGcliAdvancedTemplateTitle: "GCLI Advanced Template",
    projectGcliAdvancedTemplateDescription: "Template avançado para o GCLI, contendo autenticação, autorização, testes e documentação.",
    projectGcliAdvancedTemplateFeature1: "Autenticação e autorização",
    projectGcliAdvancedTemplateFeature2: "Testes unitários e de integração",
    projectGcliAdvancedTemplateFeature3: "Documentação com Swagger",
    projectGcliAdvancedTemplateFeature4: "Dockerização",
    projectPortfolioWebsiteTitle: "Portfolio Website",
    projectPortfolioWebsiteDescription: "Site de portfolio responsivo com animações suaves e design moderno.",
    projectPortfolioWebsiteFeature1: "Animações suaves",
    projectPortfolioWebsiteFeature2: "Design responsivo",
    projectPortfolioWebsiteFeature3: "Modo escuro",
    projectPortfolioWebsiteFeature4: "Formulário de contato",
    // New Projects
    projectTravelAppTitle: "Travel App",
    projectTravelAppDescription: "Aplicativo completo para planejamento e gerenciamento de viagens, com recursos de itinerário inteligente e compartilhamento de experiências.",
    projectTravelAppFeature1: "Planejamento de itinerários inteligente",
    projectTravelAppFeature2: "Compartilhamento e colaboração em grupo",
    projectTravelAppFeature3: "Compartilhamento de experiências",
    projectTravelAppFeature4: "Desafios de viagem gamificados",
    projectTravelAppFeature5: "Modo offline",

    projectSparkTrackerTitle: "Spark Tracker",
    projectSparkTrackerDescription: "Contador de vida avançado para Magic: The Gathering com suporte multiplayer, estatísticas detalhadas e personalização completa.",
    projectSparkTrackerFeature1: "Contador de vida para até 6 jogadores",
    projectSparkTrackerFeature2: "Rastreamento de dano de comandante",
    projectSparkTrackerFeature3: "Rastreamento de contadores e veneno",
    projectSparkTrackerFeature4: "Temas personalizáveis e modo escuro",
    projectSparkTrackerFeature5: "Suporte a iPad com interface otimizada",

    projectCookbookProTitle: "Cookbook Pro",
    projectCookbookProDescription: "Plataforma completa para descobrir, organizar e compartilhar receitas culinárias com recursos inteligentes de planejamento de refeições.",
    projectCookbookProFeature1: "Biblioteca de receitas com busca avançada",
    projectCookbookProFeature2: "Planejador de refeições semanal",
    projectCookbookProFeature3: "Lista de compras automática",
    projectCookbookProFeature4: "Compartilhamento de receitas favoritas",
    projectCookbookProFeature5: "Calculadora nutricional integrada",
    projectCookbookProFeature6: "Integração com Apple Watch",

    contact: "Entre em Contato",
    viewWork: "Conheça meu trabalho",
    contactMe: "Entre em contato",
    seeAll: "Ver Todos",
    fullstackDev: "Engenheiro de Software Sênior",
    seeProjects: "Ver projetos",
    sendMessage: "Enviar Mensagem",
    name: "Nome",
    email: "Email",
    message: "Mensagem",
    phone: "Telefone",
    location: "Localização",
    letsChat: "Vamos conversar!",
    availableFor:
      "Estou disponível para projetos freelance, oportunidades de trabalho ou apenas para trocar ideias sobre desenvolvimento web.",
    recentProjects:
      "Explore alguns dos meus trabalhos mais recentes, demonstrando minhas habilidades em desenvolvimento web full-stack.",
    mainFeatures: "Principais recursos:",
    seeMoreGithub: "Ver mais no GitHub",
    checkoutMyLinkedIn: "LinkedIn",
    fromYear: "0",
    untilYear: "Anos",
    skillDetails: "Detalhes",
    proficiencyLevel: "Tempo de experiência",
    description: "Descrição",
    clickSkill: "Clique em uma habilidade para ver mais detalhes",
    transformingIdeas: "Transformando ideias em experiências digitais excepcionais",
    frontendDev: "Desenvolvimento Frontend",
    backendDev: "Desenvolvimento Backend",
    database: "Banco de Dados",
    fullWebApps: "Aplicações Web Completas",
    yearsExperience: "anos de experiência",
    seniorAchievement1: "Liderança técnica em projetos de grande escala",
    seniorAchievement2: "Arquitetura de soluções escaláveis e resilientes",
    seniorAchievement3: "Mentoria de desenvolvedores e equipes",
    keyAchievements: "Principais Conquistas",
    careerJourney: "Trajetória Profissional",
    professionalExperience: "Experiência Profissional",
    experienceDescription:
      "Minha jornada profissional inclui trabalho com empresas inovadoras, liderando projetos desafiadores e entregando soluções de alta qualidade.",
    showMore: "Ver mais detalhes",
    showLess: "Mostrar menos",
    discussYourProject: "Vamos discutir seu projeto",
    responsibilities: "Responsabilidades",
    expWebDevelopment: "Desenvolvimento de aplicações web modernas e responsivas",
    expTeamCollaboration: "Colaboração efetiva com equipes multidisciplinares",
    expBestPractices: "Implementação de melhores práticas de desenvolvimento",
    expCodeReview: "Revisão de código e mentoria de desenvolvedores juniores",
    aboutServiceFrontend: "Criação de interfaces modernas e responsivas com React, Next.js e Tailwind CSS.",
    aboutServiceBackend: "Construção de APIs robustas e escaláveis com Node.js, Express e TypeScript.",
    aboutServiceDatabase: "Modelagem e otimização de bancos de dados SQL e NoSQL.",
    aboutServiceFullWebApps: "Desenvolvimento full-stack de aplicações web de ponta a ponta.",
    aboutIntro1: "Olá! Sou um desenvolvedor FullStack apaixonado por criar soluções web elegantes e funcionais.",
    aboutIntro2: "Olá, me chamo Vinicius. Atualmente trabalho com Stencil e .NET Core em uma empresa financeira. Uma das minhas atividades favoritas no tempo livre (além de tocar guitarra) é criar novas arquiteturas para me desafiar com novos padrões de desenvolvimento. Além disso, um dos meus hobbies é aprender novas stacks, por exemplo, agora estou bastante interessado em Golang.",
    aboutIntro3: "Nos últimos anos também tenho me interessado por aprender novos idiomas e culturas, especialmente as nórdicas. Você pode me contatar por e-mail, e se quiser ver meus projetos pessoais, confira a seção de projetos.",
    // Project media translations
    viewDemo: "Ver Demo",
    watchVideo: "Assistir Vídeo",
    liveDemo: "Demo ao Vivo",
    viewScreenshots: "Ver Capturas",
    projectGallery: "Galeria do Projeto",
    demoPreview: "Prévia da Demo",
    fullDemo: "Demo Completo",
    openInNewTab: "Abrir em Nova Aba",
    viewOnGithub: "Ver no GitHub",
    techStack: "Stack Técnica",
    projectDetails: "Detalhes do Projeto",
    closeModal: "Fechar",
    nextImage: "Próxima Imagem",
    previousImage: "Imagem Anterior",
    imageOf: "Imagem {current} de {total}",
  },
  en: {
    welcome: "Welcome to my portfolio",
    about: "About Me",
    skills: "My Skills",
    seeAllRepos: "See All Repositories",
    seeAll: "See All",
    aboutServiceFrontend: "Creating modern and responsive interfaces with React, Next.js and Tailwind CSS.",
    aboutServiceBackend: "Building robust and scalable APIs with Node.js, Express and TypeScript.",
    aboutServiceDatabase: "Modeling and optimizing SQL and NoSQL databases.",
    aboutServiceFullWebApps: "Full-stack development of end-to-end web applications.",
    aboutIntro1: "Hello! I'm a Senior Software Engineer passionate about creating elegant and functional web solutions.",
    aboutIntro2: "Hi, I'm Vinicius. Currently working with Stencil and .NET Core at a financial company. One of my favorite things to do on my free time (besides playing the guitar) is to build new architectures in order to challenge myself with new development patterns. Besides, one of my hobbies includes learning new stacks, for instance, right now I'm quite interested in Golang.",
    aboutIntro3: "For the past few years I've also been interested in learning new languages and cultures, especially the nordic ones. You can reach me at my e-mail, if you want to see my personal projects, check out projects section.",
    projects: "Recent Projects",
    exp1Title: "Senior Software Engineer",
    exp1Company: "Riverty",
    exp1CompanyUrl: "https://riverty.com",
    exp1Location: "Tallinn, Estonia",
    exp1Period: "2022 - Present",
    exp1Description: "Web application development with React and Next.js. Design system implementation and performance optimization.",
    exp2Title: "Software Engineer",
    exp2Company: "Arvato Financial Solutions Tech Center",
    exp2CompanyUrl: "https://arvato.com",
    exp2Location: "Tallinn, Estonia",
    exp2Period: "2022 - 2022",
    exp2Description: "Web application development with React and Next.js. Design system implementation and performance optimization.",
    exp3Title: "Full Stack Developer",
    exp3Company: "MAGIT IT PARTNER",
    exp3Location: "Ribeirão Preto, Brazil",
    exp3Period: "2020 - 2022",
    exp3Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp4Title: "Full Stack Developer",
    exp4Company: "GooWe",
    exp4Location: "Ribeirão Preto, Brazil",
    exp4Period: "2019 - 2020",
    exp4Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp5Title: "Full Stack Developer",
    exp5Company: "Kezz IT",
    exp5Location: "Ribeirão Preto, Brazil",
    exp5Period: "2019 - 2019",
    exp5Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp6Title: "Full Stack Developer",
    exp6Company: "Onsoft Web",
    exp6Location: "Ribeirão Preto, Brazil",
    exp6Period: "2018 - 2019",
    exp6Description: "Development of responsive websites and landing pages for clients from various sectors.",
    exp7Title: "Web Freelancer",
    exp7Company: "Freelance",
    exp7Location: "Ribeirão Preto, Brazil",
    exp7Period: "2018 - 2019",
    exp7Description: "Development of responsive websites and landing pages for clients from various sectors.",
    skillCSharpName: "C#",
    skillCSharpCategory: "Languages",
    skillCSharpDescription: "Financial systems architecture with .NET Core, scalable microservices and Kafka integration. +7 years developing robust APIs for high-volume processing.",
    skillGoName: "Go",
    skillGoCategory: "Languages",
    skillGoDescription: "Building robust CLI tools and high-performance microservices. Creator of GCLI with 32 stars, expert in concurrency and distributed systems.",
    skillTypeScriptName: "TypeScript",
    skillTypeScriptCategory: "Languages",
    skillTypeScriptDescription: "Enterprise Web Components development with Stencil.js in financial environment. Specialist in full-stack type-safe applications and scalable architecture.",
    skillAngularName: "Angular",
    skillAngularCategory: "Frontend",
    skillAngularDescription: "Complex SPA development and design systems. Web Components integration and advanced state management for enterprise applications.",
    skillIonicName: "Ionic",
    skillIonicCategory: "Mobile",
    skillIonicDescription: "Cross-platform hybrid app development with Angular and Capacitor. Experience in publishing and optimization for iOS and Android.",
    skillSwiftUIName: "SwiftUI",
    skillSwiftUICategory: "Mobile",
    skillSwiftUIDescription: "Native iOS development with SwiftUI and Combine. Currently dedicating 59% of development time to Swift projects, creating modern and performant interfaces.",
    skillStencilJSName: "StencilJS",
    skillStencilJSCategory: "Frontend",
    skillStencilJSDescription: "Enterprise Web Components for financial systems at Riverty. Building reusable design systems and high-performance components for critical applications.",
    skillMongoDBName: "MongoDB",
    skillMongoDBCategory: "Database",
    skillMongoDBDescription: "NoSQL data modeling for high-volume systems. Query optimization and sharding strategies implementation for scalable financial applications.",
    skillSQLServerName: "SQLServer",
    skillSQLServerCategory: "Database",
    skillSQLServerDescription: "SQL database administration, query and procedure optimization.",
    skillOracleName: "Oracle",
    skillOracleCategory: "Database",
    skillOracleDescription: "Managing large volumes of data and PL/SQL for automation.",
    skillDockerName: "Docker",
    skillDockerCategory: "DevOps",
    skillDockerDescription: "Microservices containerization and complex environments orchestration. CI/CD pipelines implementation and infrastructure management for financial applications.",
    skillKubernetesName: "Kubernetes",
    skillKubernetesCategory: "DevOps",
    skillKubernetesDescription: "Container orchestration, autoscaling, and resilient deployments.",
    skillBicepName: "Bicep",
    skillBicepCategory: "DevOps",
    skillBicepDescription: "Infrastructure as Code for production Azure deployments. Resource provisioning automation and environment management for enterprise applications.",
    skillTerraformName: "Terraform",
    skillTerraformCategory: "DevOps",
    skillTerraformDescription: "Multi-cloud infrastructure automation and state management.",
    projectUrlShortenerTitle: "URL-Shortener",
    projectUrlShortenerDescription: "Platform for shortening URLs, capable of supporting a large volume of data, deployed on Azure.",
    projectUrlShortenerFeature1: "Short URL generation",
    projectUrlShortenerFeature2: "URL redirection",
    projectUrlShortenerFeature3: "Access statistics",
    projectUrlShortenerFeature4: "Observability",
    projectGcliTitle: "GCLI",
    projectGcliDescription: "CLI in Golang for creating Golang projects, already containing a robust and production-ready structure.",
    projectGcliFeature1: "Create Golang projects with multiple templates",
    projectGcliFeature2: "Simplified CRUD generation",
    projectGcliFeature3: "Migration server with Hot Reload",
    projectGcliFeature4: "Project Dockerization",
    projectGcliFeature5: "Production ready",
    projectMtgCardInventoryTitle: "MTG Card Inventory",
    projectMtgCardInventoryDescription: "App for managing Magic The Gathering card inventory and decks.",
    projectMtgCardInventoryFeature1: "Cataloged card listing with advanced filters",
    projectMtgCardInventoryFeature2: "Custom deck creation",
    projectMtgCardInventoryFeature3: "Remote database sync",
    projectGcliAdvancedTemplateTitle: "GCLI Advanced Template",
    projectGcliAdvancedTemplateDescription: "Advanced template for GCLI, including authentication, authorization, tests, and documentation.",
    projectGcliAdvancedTemplateFeature1: "Authentication and authorization",
    projectGcliAdvancedTemplateFeature2: "Unit and integration tests",
    projectGcliAdvancedTemplateFeature3: "Swagger documentation",
    projectGcliAdvancedTemplateFeature4: "Dockerization",
    projectPortfolioWebsiteTitle: "Portfolio Website",
    projectPortfolioWebsiteDescription: "Responsive portfolio website with smooth animations and modern design.",
    projectPortfolioWebsiteFeature1: "Smooth animations",
    projectPortfolioWebsiteFeature2: "Responsive design",
    projectPortfolioWebsiteFeature3: "Dark mode",
    projectPortfolioWebsiteFeature4: "Contact form",

    projectTravelAppTitle: "Travel App",
    projectTravelAppDescription: "Complete travel planning and management app with smart itinerary features and experience sharing capabilities.",
    projectTravelAppFeature1: "Smart itinerary planning",
    projectTravelAppFeature2: "Group sharing and collaboration",
    projectTravelAppFeature3: "Experience sharing platform",
    projectTravelAppFeature4: "Gamified travel challenges",
    projectTravelAppFeature5: "Offline mode",

    projectSparkTrackerTitle: "Spark Tracker",
    projectSparkTrackerDescription: "Advanced life counter for Magic: The Gathering with multiplayer support, detailed statistics and complete customization.",
    projectSparkTrackerFeature1: "Life counter for up to 6 players",
    projectSparkTrackerFeature2: "Commander damage tracking",
    projectSparkTrackerFeature3: "Counters and poison tracking",
    projectSparkTrackerFeature4: "Customizable themes and dark mode",
    projectSparkTrackerFeature5: "iPad support with optimized interface",

    projectCookbookProTitle: "Cookbook Pro",
    projectCookbookProDescription: "Complete platform for discovering, organizing and sharing culinary recipes with intelligent meal planning features.",
    projectCookbookProFeature1: "Recipe library with advanced search",
    projectCookbookProFeature2: "Weekly meal planner",
    projectCookbookProFeature3: "Automatic shopping lists",
    projectCookbookProFeature4: "Favorite recipe sharing",
    projectCookbookProFeature5: "Integrated nutrition calculator",
    projectCookbookProFeature6: "Apple Watch Integration",

    contact: "Contact Me",
    viewWork: "View my work",
    contactMe: "Contact me",
    fullstackDev: "Senior Software Engineer",
    seeProjects: "See projects",
    sendMessage: "Send Message",
    name: "Name",
    email: "Email",
    message: "Message",
    phone: "Phone",
    location: "Location",
    letsChat: "Let's chat!",
    availableFor:
      "I'm available for freelance projects, job opportunities, or just to exchange ideas about web development.",
    recentProjects: "Explore some of my recent work, showcasing my skills in full-stack web development.",
    mainFeatures: "Main features:",
    seeMoreGithub: "See more on GitHub",
    checkoutMyLinkedIn: "LinkedIn",
    fromYear: "0",
    untilYear: "Years",
    skillDetails: "Details",
    proficiencyLevel: "Experience Time",
    description: "Description",
    clickSkill: "Click on a skill to see more details",
    transformingIdeas: "Transforming ideas into exceptional digital experiences",
    frontendDev: "Frontend Development",
    backendDev: "Backend Development",
    database: "Database",
    fullWebApps: "Full Web Applications",
    yearsExperience: "years of experience",
    seniorAchievement1: "Technical leadership in large-scale projects",
    seniorAchievement2: "Architecture of scalable and resilient solutions",
    seniorAchievement3: "Mentoring developers and teams",
    keyAchievements: "Key Achievements",
    careerJourney: "Career Journey",
    professionalExperience: "Professional Experience",
    experienceDescription:
      "My professional journey includes work with innovative companies, leading challenging projects and delivering high-quality solutions.",
    showMore: "Show more details",
    showLess: "Show less",
    discussYourProject: "Let's discuss your project",
    responsibilities: "Responsibilities",
    expWebDevelopment: "Development of modern and responsive web applications",
    expTeamCollaboration: "Effective collaboration with multidisciplinary teams",
    expBestPractices: "Implementation of development best practices",
    expCodeReview: "Code review and mentoring of junior developers",
    // Project media translations
    viewDemo: "View Demo",
    watchVideo: "Watch Video",
    liveDemo: "Live Demo",
    viewScreenshots: "View Screenshots",
    projectGallery: "Project Gallery",
    demoPreview: "Demo Preview",
    fullDemo: "Full Demo",
    openInNewTab: "Open in New Tab",
    viewOnGithub: "View on GitHub",
    techStack: "Tech Stack",
    projectDetails: "Project Details",
    closeModal: "Close",
    nextImage: "Next Image",
    previousImage: "Previous Image",
    imageOf: "Image {current} of {total}",
  },
  ru: {
    welcome: "Добро пожаловать в мое портфолио",
    about: "Обо мне",
    seeAllRepos: "Посмотреть все репозитории",
    skills: "Мои навыки",
    seeAll: "Посмотреть все",
    projects: "Недавние проекты",
    contact: "Связаться со мной",
    viewWork: "Посмотреть мои работы",
    contactMe: "Связаться со мной",
    fullstackDev: "Старший инженер-программист",
    seeProjects: "Посмотреть проекты",
    sendMessage: "Отправить сообщение",
    name: "Имя",
    email: "Электронная почта",
    message: "Сообщение",
    phone: "Телефон",
    location: "Местоположение",
    letsChat: "Давайте пообщаемся!",
    availableFor: "Я доступен для фриланс-проектов, предложений работы или просто для обмена идеями о веб-разработке.",
    recentProjects: "Ознакомьтесь с некоторыми из моих последних работ, демонстрирующих мои навыки в full-stack веб-разработке.",
    mainFeatures: "Основные функции:",
    seeMoreGithub: "Смотреть больше на GitHub",
    checkoutMyLinkedIn: "LinkedIn",
    aboutServiceFrontend: "Создание современных и адаптивных интерфейсов с помощью React, Next.js и Tailwind CSS.",
    aboutServiceBackend: "Разработка надёжных и масштабируемых API с Node.js, Express и TypeScript.",
    aboutServiceDatabase: "Моделирование и оптимизация SQL и NoSQL баз данных.",
    aboutServiceFullWebApps: "Full-stack разработка веб-приложений от начала до конца.",
    aboutIntro1: "Привет! Я FullStack-разработчик, увлечённый созданием элегантных и функциональных веб-решений.",
    aboutIntro2: "Привет, я Винисиус. Сейчас работаю со Stencil и .NET Core в финансовой компании. В свободное время (кроме игры на гитаре) люблю строить новые архитектуры, чтобы бросать себе вызов новыми паттернами разработки. Также мне нравится изучать новые стеки — например, сейчас интересуюсь Golang.",
    aboutIntro3: "В последние годы я также интересуюсь изучением новых языков и культур, особенно северных. Связаться со мной можно по e-mail, а если хотите увидеть мои личные проекты — смотрите раздел проектов.",
    fromYear: "0",
    untilYear: "Лет",
    skillDetails: "Детали",
    proficiencyLevel: "Опыт работы",
    description: "Описание",
    clickSkill: "Нажмите на навык, чтобы увидеть подробности",
    transformingIdeas: "Превращаю идеи в исключительный цифровой опыт",
    frontendDev: "Фронтенд-разработка",
    backendDev: "Бэкенд-разработка",
    database: "Базы данных",
    fullWebApps: "Полные веб-приложения",
    yearsExperience: "лет опыта",
    seniorAchievement1: "Техническое руководство в крупномасштабных проектах",
    seniorAchievement2: "Архитектура масштабируемых и отказоустойчивых решений",
    seniorAchievement3: "Наставничество разработчиков и команд",
    careerJourney: "Карьерный путь",
    professionalExperience: "Профессиональный опыт",
    experienceDescription:
      "Мой профессиональный путь включает работу с инновационными компаниями, руководство сложными проектами и предоставление высококачественных решений.",
    keyAchievements: "Ключевые достижения",
    showMore: "Показать подробности",
    showLess: "Свернуть",
    discussYourProject: "Давайте обсудим ваш проект",
    responsibilities: "Обязанности",
    expWebDevelopment: "Разработка современных и адаптивных веб-приложений",
    expTeamCollaboration: "Эффективное сотрудничество с мультидисциплинарными командами",
    expBestPractices: "Внедрение лучших практик разработки",
    expCodeReview: "Ревью кода и наставничество младших разработчиков",
    // Experience
    exp1Title: "Старший инженер-программист",
    exp1Company: "Riverty",
    exp1CompanyUrl: "https://riverty.com",
    exp1Location: "Таллин, Эстония",
    exp1Period: "2022 - Настоящее время",
    exp1Description: "Разработка веб-приложений с React и Next.js. Внедрение дизайн-систем и оптимизация производительности.",
    exp2Title: "Инженер-программист",
    exp2Company: "Arvato Financial Solutions Tech Center",
    exp2CompanyUrl: "https://arvato.com",
    exp2Location: "Таллин, Эстония",
    exp2Period: "2022 - 2022",
    exp2Description: "Разработка веб-приложений с React и Next.js. Внедрение дизайн-систем и оптимизация производительности.",
    exp3Title: "Full Stack разработчик",
    exp3Company: "MAGIT IT PARTNER",
    exp3Location: "Рибейран-Прету, Бразилия",
    exp3Period: "2020 - 2022",
    exp3Description: "Разработка адаптивных сайтов и лендинг-страниц для клиентов из различных отраслей.",
    exp4Title: "Full Stack разработчик",
    exp4Company: "GooWe",
    exp4Location: "Рибейран-Прету, Бразилия",
    exp4Period: "2019 - 2020",
    exp4Description: "Разработка адаптивных сайтов и лендинг-страниц для клиентов из различных отраслей.",
    exp5Title: "Full Stack разработчик",
    exp5Company: "Kezz IT",
    exp5Location: "Рибейран-Прету, Бразилия",
    exp5Period: "2019 - 2019",
    exp5Description: "Разработка адаптивных сайтов и лендинг-страниц для клиентов из различных отраслей.",
    exp6Title: "Full Stack разработчик",
    exp6Company: "Onsoft Web",
    exp6Location: "Рибейран-Прету, Бразилия",
    exp6Period: "2018 - 2019",
    exp6Description: "Разработка адаптивных сайтов и лендинг-страниц для клиентов из различных отраслей.",
    exp7Title: "Веб-фрилансер",
    exp7Company: "Фриланс",
    exp7Location: "Рибейран-Прету, Бразилия",
    exp7Period: "2018 - 2019",
    exp7Description: "Разработка адаптивных сайтов и лендинг-страниц для клиентов из различных отраслей.",
    // Skills
    skillCSharpName: "C#",
    skillCSharpCategory: "Языки",
    skillCSharpDescription: "Архитектура критических финансовых систем на .NET Core, масштабируемые микросервисы и интеграция с Kafka. Более 7 лет разработки надёжных API для высоконагруженных систем.",
    skillGoName: "Go",
    skillGoCategory: "Языки",
    skillGoDescription: "Создание надёжных CLI-инструментов и высокопроизводительных микросервисов. Автор GCLI с 32 звёздами, эксперт в конкурентности и распределённых системах.",
    skillTypeScriptName: "TypeScript",
    skillTypeScriptCategory: "Языки",
    skillTypeScriptDescription: "Разработка корпоративных веб-компонентов со Stencil.js в финансовой среде. Специалист по типобезопасным full-stack приложениям и масштабируемой архитектуре.",
    skillAngularName: "Angular",
    skillAngularCategory: "Фронтенд",
    skillAngularDescription: "Разработка сложных SPA и дизайн-систем. Интеграция веб-компонентов и продвинутое управление состоянием для корпоративных приложений.",
    skillIonicName: "Ionic",
    skillIonicCategory: "Мобильные",
    skillIonicDescription: "Разработка кроссплатформенных гибридных приложений с Angular и Capacitor. Опыт публикации и оптимизации для iOS и Android.",
    skillSwiftUIName: "SwiftUI",
    skillSwiftUICategory: "Мобильные",
    skillSwiftUIDescription: "Нативная разработка iOS с SwiftUI и Combine. В настоящее время 59% времени разработки посвящается проектам на Swift, создание современных и производительных интерфейсов.",
    skillStencilJSName: "StencilJS",
    skillStencilJSCategory: "Фронтенд",
    skillStencilJSDescription: "Корпоративные веб-компоненты для финансовых систем в Riverty. Создание переиспользуемых дизайн-систем и высокопроизводительных компонентов для критических приложений.",
    skillMongoDBName: "MongoDB",
    skillMongoDBCategory: "Базы данных",
    skillMongoDBDescription: "Моделирование данных NoSQL для высоконагруженных систем. Оптимизация запросов и реализация стратегий шардирования для масштабируемых финансовых приложений.",
    skillSQLServerName: "SQLServer",
    skillSQLServerCategory: "Базы данных",
    skillSQLServerDescription: "Администрирование баз данных SQL, оптимизация запросов и хранимых процедур.",
    skillOracleName: "Oracle",
    skillOracleCategory: "Базы данных",
    skillOracleDescription: "Управление большими объёмами данных и PL/SQL для автоматизации.",
    skillDockerName: "Docker",
    skillDockerCategory: "DevOps",
    skillDockerDescription: "Контейнеризация микросервисов и оркестрация сложных сред. Реализация CI/CD пайплайнов и управление инфраструктурой для финансовых приложений.",
    skillKubernetesName: "Kubernetes",
    skillKubernetesCategory: "DevOps",
    skillKubernetesDescription: "Оркестрация контейнеров, автомасштабирование и отказоустойчивые развёртывания.",
    skillBicepName: "Bicep",
    skillBicepCategory: "DevOps",
    skillBicepDescription: "Инфраструктура как код для продакшн-развёртываний в Azure. Автоматизация подготовки ресурсов и управление средами для корпоративных приложений.",
    skillTerraformName: "Terraform",
    skillTerraformCategory: "DevOps",
    skillTerraformDescription: "Автоматизация мультиоблачной инфраструктуры и управление состоянием.",
    // Projects
    projectUrlShortenerTitle: "URL-Shortener",
    projectUrlShortenerDescription: "Платформа для сокращения URL-адресов, способная обрабатывать большой объём данных, развёрнутая в Azure.",
    projectUrlShortenerFeature1: "Генерация коротких URL",
    projectUrlShortenerFeature2: "Перенаправление URL",
    projectUrlShortenerFeature3: "Статистика доступа",
    projectUrlShortenerFeature4: "Наблюдаемость",
    projectGcliTitle: "GCLI",
    projectGcliDescription: "CLI на Golang для создания проектов на Golang с надёжной структурой, готовой к продакшну.",
    projectGcliFeature1: "Создание проектов на Golang с несколькими шаблонами",
    projectGcliFeature2: "Упрощённая генерация CRUD",
    projectGcliFeature3: "Сервер миграций с горячей перезагрузкой",
    projectGcliFeature4: "Докеризация проекта",
    projectGcliFeature5: "Готовность к продакшну",
    projectMtgCardInventoryTitle: "MTG Card Inventory",
    projectMtgCardInventoryDescription: "Приложение для управления инвентарём и колодами карт Magic: The Gathering.",
    projectMtgCardInventoryFeature1: "Каталог карт с расширенными фильтрами",
    projectMtgCardInventoryFeature2: "Создание пользовательских колод",
    projectMtgCardInventoryFeature3: "Синхронизация с удалённой базой данных",
    projectGcliAdvancedTemplateTitle: "GCLI Advanced Template",
    projectGcliAdvancedTemplateDescription: "Расширенный шаблон для GCLI, включающий аутентификацию, авторизацию, тесты и документацию.",
    projectGcliAdvancedTemplateFeature1: "Аутентификация и авторизация",
    projectGcliAdvancedTemplateFeature2: "Юнит- и интеграционные тесты",
    projectGcliAdvancedTemplateFeature3: "Документация Swagger",
    projectGcliAdvancedTemplateFeature4: "Докеризация",
    projectPortfolioWebsiteTitle: "Portfolio Website",
    projectPortfolioWebsiteDescription: "Адаптивный сайт-портфолио с плавными анимациями и современным дизайном.",
    projectPortfolioWebsiteFeature1: "Плавные анимации",
    projectPortfolioWebsiteFeature2: "Адаптивный дизайн",
    projectPortfolioWebsiteFeature3: "Тёмная тема",
    projectPortfolioWebsiteFeature4: "Форма обратной связи",
    projectTravelAppTitle: "Travel App",
    projectTravelAppDescription: "Полноценное приложение для планирования и управления путешествиями с интеллектуальным построением маршрутов и обменом впечатлениями.",
    projectTravelAppFeature1: "Интеллектуальное планирование маршрутов",
    projectTravelAppFeature2: "Групповой обмен и совместная работа",
    projectTravelAppFeature3: "Платформа обмена впечатлениями",
    projectTravelAppFeature4: "Геймифицированные тревел-челленджи",
    projectTravelAppFeature5: "Офлайн-режим",
    projectSparkTrackerTitle: "Spark Tracker",
    projectSparkTrackerDescription: "Продвинутый счётчик жизней для Magic: The Gathering с поддержкой мультиплеера, подробной статистикой и полной настройкой.",
    projectSparkTrackerFeature1: "Счётчик жизней для до 6 игроков",
    projectSparkTrackerFeature2: "Отслеживание урона командира",
    projectSparkTrackerFeature3: "Отслеживание жетонов и отравления",
    projectSparkTrackerFeature4: "Настраиваемые темы и тёмный режим",
    projectSparkTrackerFeature5: "Поддержка iPad с оптимизированным интерфейсом",
    projectCookbookProTitle: "Cookbook Pro",
    projectCookbookProDescription: "Полноценная платформа для поиска, организации и обмена кулинарными рецептами с интеллектуальным планированием питания.",
    projectCookbookProFeature1: "Библиотека рецептов с расширенным поиском",
    projectCookbookProFeature2: "Планировщик питания на неделю",
    projectCookbookProFeature3: "Автоматический список покупок",
    projectCookbookProFeature4: "Обмен любимыми рецептами",
    projectCookbookProFeature5: "Встроенный калькулятор питательной ценности",
    projectCookbookProFeature6: "Интеграция с Apple Watch",
    // Project media translations
    viewDemo: "Посмотреть демо",
    watchVideo: "Смотреть видео",
    liveDemo: "Живое демо",
    viewScreenshots: "Посмотреть скриншоты",
    projectGallery: "Галерея проекта",
    demoPreview: "Превью демо",
    fullDemo: "Полное демо",
    openInNewTab: "Открыть в новой вкладке",
    viewOnGithub: "Посмотреть на GitHub",
    techStack: "Технологический стек",
    projectDetails: "Детали проекта",
    closeModal: "Закрыть",
    nextImage: "Следующее изображение",
    previousImage: "Предыдущее изображение",
    imageOf: "Изображение {current} из {total}",
  },
  et: {
    welcome: "Tere tulemast minu portfooliosse",
    about: "Minust",
    skills: "Minu oskused",
    seeAllRepos: "Vaata kõiki repositooriume",
    projects: "Viimased projektid",
    seeAll: "Vaata kõiki",
    contact: "Võta ühendust",
    viewWork: "Vaata minu tööd",
    contactMe: "Võta minuga ühendust",
    fullstackDev: "Vanemtarkvarainsener",
    seeProjects: "Vaata projekte",
    sendMessage: "Saada sõnum",
    name: "Nimi",
    email: "E-post",
    message: "Sõnum",
    phone: "Telefon",
    location: "Asukoht",
    letsChat: "Räägime!",
    availableFor:
      "Olen saadaval vabakutseliste projektide, tööpakkumiste jaoks või lihtsalt veebiarenduse ideede vahetamiseks.",
    recentProjects: "Tutvu mõnede minu viimaste töödega, mis näitavad minu oskusi full-stack veebiarenduses.",
    mainFeatures: "Peamised funktsioonid:",
    seeMoreGithub: "Vaata rohkem GitHubis",
    checkoutMyLinkedIn: "LinkedIn",
    fromYear: "0",
    aboutServiceFrontend: "Kaasaegsete ja responsiivste liideste loomine Reacti, Next.js-i ja Tailwind CSS-iga.",
    aboutServiceBackend: "Tugevate ja skaleeritavate API-de loomine Node.js, Expressi ja TypeScriptiga.",
    aboutServiceDatabase: "SQL ja NoSQL andmebaaside modelleerimine ja optimeerimine.",
    aboutServiceFullWebApps: "Full-stack veebirakenduste arendamine algusest lõpuni.",
    aboutIntro1: "Tere! Olen FullStack-arendaja, kelle kirg on luua elegantseid ja funktsionaalseid veebilahendusi.",
    aboutIntro2: "Tere, mina olen Vinicius. Töötan praegu Stenciliga ja .NET Core'iga finantsettevõttes. Vabal ajal (peale kitarri mängimise) meeldib mulle ehitada uusi arhitektuure, et end proovile panna uute arendusmustritega. Lisaks on minu hobiks uute stackide õppimine — näiteks praegu huvitab mind Golang.",
    aboutIntro3: "Viimastel aastatel olen huvitunud ka uute keelte ja kultuuride õppimisest, eriti põhjamaistest. Võid minuga ühendust võtta e-posti teel. Kui tahad näha minu isiklikke projekte, vaata projektide sektsiooni.",
    untilYear: "Aastat",
    skillDetails: "Üksikasjad",
    proficiencyLevel: "Kogemuse aeg",
    description: "Kirjeldus",
    clickSkill: "Klõpsa oskusel, et näha rohkem üksikasju",
    transformingIdeas: "Muudan ideed erakordseteks digitaalseteks kogemusteks",
    frontendDev: "Frontendi arendus",
    backendDev: "Backendi arendus",
    database: "Andmebaasid",
    fullWebApps: "Täielikud veebirakendused",
    yearsExperience: "aastat kogemust",
    seniorAchievement1: "Tehniline juhtimine suuremahulistes projektides",
    seniorAchievement2: "Skaleeritavate ja vastupidavate lahenduste arhitektuur",
    seniorAchievement3: "Arendajate ja meeskondade juhendamine",
    keyAchievements: "Peamised saavutused",
    careerJourney: "Karjääritee",
    professionalExperience: "Töökogemus",
    experienceDescription:
      "Minu professionaalne teekond hõlmab tööd innovaatiliste ettevõtetega, keeruliste projektide juhtimist ja kvaliteetsete lahenduste pakkumist.",
    showMore: "Näita rohkem üksikasju",
    showLess: "Näita vähem",
    discussYourProject: "Arutame teie projekti",
    responsibilities: "Kohustused",
    expWebDevelopment: "Kaasaegsete ja responsiivste veebirakenduste arendamine",
    expTeamCollaboration: "Tõhus koostöö multidistsiplinaarsete meeskondadega",
    expBestPractices: "Arenduse parimate tavade rakendamine",
    expCodeReview: "Koodi ülevaatus ja nooremarendajate juhendamine",
    // Experience
    exp1Title: "Vanemtarkvarainsener",
    exp1Company: "Riverty",
    exp1CompanyUrl: "https://riverty.com",
    exp1Location: "Tallinn, Eesti",
    exp1Period: "2022 - Praegu",
    exp1Description: "Veebirakenduste arendamine Reacti ja Next.js-iga. Disainisüsteemide juurutamine ja jõudluse optimeerimine.",
    exp2Title: "Tarkvarainsener",
    exp2Company: "Arvato Financial Solutions Tech Center",
    exp2CompanyUrl: "https://arvato.com",
    exp2Location: "Tallinn, Eesti",
    exp2Period: "2022 - 2022",
    exp2Description: "Veebirakenduste arendamine Reacti ja Next.js-iga. Disainisüsteemide juurutamine ja jõudluse optimeerimine.",
    exp3Title: "Full Stack arendaja",
    exp3Company: "MAGIT IT PARTNER",
    exp3Location: "Ribeirão Preto, Brasiilia",
    exp3Period: "2020 - 2022",
    exp3Description: "Responsiivste veebisaitide ja maandumislehtede arendamine erinevatest sektoritest pärit klientidele.",
    exp4Title: "Full Stack arendaja",
    exp4Company: "GooWe",
    exp4Location: "Ribeirão Preto, Brasiilia",
    exp4Period: "2019 - 2020",
    exp4Description: "Responsiivste veebisaitide ja maandumislehtede arendamine erinevatest sektoritest pärit klientidele.",
    exp5Title: "Full Stack arendaja",
    exp5Company: "Kezz IT",
    exp5Location: "Ribeirão Preto, Brasiilia",
    exp5Period: "2019 - 2019",
    exp5Description: "Responsiivste veebisaitide ja maandumislehtede arendamine erinevatest sektoritest pärit klientidele.",
    exp6Title: "Full Stack arendaja",
    exp6Company: "Onsoft Web",
    exp6Location: "Ribeirão Preto, Brasiilia",
    exp6Period: "2018 - 2019",
    exp6Description: "Responsiivste veebisaitide ja maandumislehtede arendamine erinevatest sektoritest pärit klientidele.",
    exp7Title: "Veebi vabakutseline",
    exp7Company: "Vabakutseline",
    exp7Location: "Ribeirão Preto, Brasiilia",
    exp7Period: "2018 - 2019",
    exp7Description: "Responsiivste veebisaitide ja maandumislehtede arendamine erinevatest sektoritest pärit klientidele.",
    // Skills
    skillCSharpName: "C#",
    skillCSharpCategory: "Keeled",
    skillCSharpDescription: "Kriitiliste finantssüsteemide arhitektuur .NET Core'iga, skaleeritavad mikroteenused ja Kafka integratsioon. Üle 7 aasta kogemust tugevate API-de arendamisel suure mahuga töötlemiseks.",
    skillGoName: "Go",
    skillGoCategory: "Keeled",
    skillGoDescription: "Tugevate CLI-tööriistade ja suure jõudlusega mikroteenuste loomine. GCLI autor 32 tähega, ekspert samaaegsuses ja hajutatud süsteemides.",
    skillTypeScriptName: "TypeScript",
    skillTypeScriptCategory: "Keeled",
    skillTypeScriptDescription: "Ettevõtte veebikomponentide arendamine Stencil.js-iga finantskeskkonnas. Spetsialist tüübiturvaste full-stack rakenduste ja skaleeritava arhitektuuri alal.",
    skillAngularName: "Angular",
    skillAngularCategory: "Frontend",
    skillAngularDescription: "Keerukate SPA-de ja disainisüsteemide arendamine. Veebikomponentide integratsioon ja täiustatud olekuhaldus ettevõtterakenduste jaoks.",
    skillIonicName: "Ionic",
    skillIonicCategory: "Mobiil",
    skillIonicDescription: "Platvormideüleste hübriidrakenduste arendamine Angulari ja Capacitoriga. Kogemus avaldamisel ja optimeerimisel iOS-ile ja Androidile.",
    skillSwiftUIName: "SwiftUI",
    skillSwiftUICategory: "Mobiil",
    skillSwiftUIDescription: "Natiivne iOS-i arendus SwiftUI ja Combine'iga. Praegu pühendatakse 59% arendusajast Swifti projektidele, luues kaasaegseid ja jõudlusrikkaid liideseid.",
    skillStencilJSName: "StencilJS",
    skillStencilJSCategory: "Frontend",
    skillStencilJSDescription: "Ettevõtte veebikomponendid finantssüsteemide jaoks Rivertys. Taaskasutatavate disainisüsteemide ja suure jõudlusega komponentide loomine kriitiliste rakenduste jaoks.",
    skillMongoDBName: "MongoDB",
    skillMongoDBCategory: "Andmebaasid",
    skillMongoDBDescription: "NoSQL andmete modelleerimine suure mahuga süsteemide jaoks. Päringute optimeerimine ja sharding-strateegiate rakendamine skaleeritavatele finantsrakendustele.",
    skillSQLServerName: "SQLServer",
    skillSQLServerCategory: "Andmebaasid",
    skillSQLServerDescription: "SQL andmebaaside haldamine, päringute ja protseduuride optimeerimine.",
    skillOracleName: "Oracle",
    skillOracleCategory: "Andmebaasid",
    skillOracleDescription: "Suurte andmemahtude haldamine ja PL/SQL automatiseerimiseks.",
    skillDockerName: "Docker",
    skillDockerCategory: "DevOps",
    skillDockerDescription: "Mikroteenuste konteineriseerimine ja keerukate keskkondade orkestreerimine. CI/CD torustike juurutamine ja taristu haldamine finantsrakenduste jaoks.",
    skillKubernetesName: "Kubernetes",
    skillKubernetesCategory: "DevOps",
    skillKubernetesDescription: "Konteinerite orkestreerimine, automaatne skaleerimine ja vastupidavad juurutused.",
    skillBicepName: "Bicep",
    skillBicepCategory: "DevOps",
    skillBicepDescription: "Taristu koodina Azure'i tootmisjuurutuste jaoks. Ressursside ettevalmistamise automatiseerimine ja keskkondade haldamine ettevõtterakenduste jaoks.",
    skillTerraformName: "Terraform",
    skillTerraformCategory: "DevOps",
    skillTerraformDescription: "Mitme pilve taristu automatiseerimine ja olekuhaldus.",
    // Projects
    projectUrlShortenerTitle: "URL-Shortener",
    projectUrlShortenerDescription: "URL-ide lühendamise platvorm, mis suudab töödelda suurt andmemahtu, juurutatud Azure'is.",
    projectUrlShortenerFeature1: "Lühikeste URL-ide genereerimine",
    projectUrlShortenerFeature2: "URL-ide ümbersuunamine",
    projectUrlShortenerFeature3: "Juurdepääsu statistika",
    projectUrlShortenerFeature4: "Jälgitavus",
    projectGcliTitle: "GCLI",
    projectGcliDescription: "CLI Golangis Golangi projektide loomiseks, sisaldab juba tugevat ja tootmisvalmis struktuuri.",
    projectGcliFeature1: "Golangi projektide loomine mitme malliga",
    projectGcliFeature2: "Lihtsustatud CRUD genereerimine",
    projectGcliFeature3: "Migratsiooniserveriga kuumlaadimine",
    projectGcliFeature4: "Projekti dokeriseermine",
    projectGcliFeature5: "Tootmisvalmidus",
    projectMtgCardInventoryTitle: "MTG Card Inventory",
    projectMtgCardInventoryDescription: "Rakendus Magic: The Gathering kaartide inventari ja pakkide haldamiseks.",
    projectMtgCardInventoryFeature1: "Kataloogitud kaartide loend täiustatud filtritega",
    projectMtgCardInventoryFeature2: "Kohandatud pakkide loomine",
    projectMtgCardInventoryFeature3: "Kaugandmebaasi sünkroniseerimine",
    projectGcliAdvancedTemplateTitle: "GCLI Advanced Template",
    projectGcliAdvancedTemplateDescription: "Täiustatud mall GCLI jaoks, sisaldab autentimist, autoriseerimist, teste ja dokumentatsiooni.",
    projectGcliAdvancedTemplateFeature1: "Autentimine ja autoriseerimine",
    projectGcliAdvancedTemplateFeature2: "Ühik- ja integratsioonitestid",
    projectGcliAdvancedTemplateFeature3: "Swaggeri dokumentatsioon",
    projectGcliAdvancedTemplateFeature4: "Dokeriseermine",
    projectPortfolioWebsiteTitle: "Portfolio Website",
    projectPortfolioWebsiteDescription: "Responsiivne portfoolio veebisait sujuvate animatsioonide ja kaasaegse disainiga.",
    projectPortfolioWebsiteFeature1: "Sujuvad animatsioonid",
    projectPortfolioWebsiteFeature2: "Responsiivne disain",
    projectPortfolioWebsiteFeature3: "Tume režiim",
    projectPortfolioWebsiteFeature4: "Kontaktivorm",
    projectTravelAppTitle: "Travel App",
    projectTravelAppDescription: "Täielik reisiplaneerimise ja -haldamise rakendus nutikate marsruudi funktsioonide ja kogemuste jagamise võimalustega.",
    projectTravelAppFeature1: "Nutikas marsruudi planeerimine",
    projectTravelAppFeature2: "Grupi jagamine ja koostöö",
    projectTravelAppFeature3: "Kogemuste jagamise platvorm",
    projectTravelAppFeature4: "Mängustatud reiside väljakutsed",
    projectTravelAppFeature5: "Võrguühenduseta režiim",
    projectSparkTrackerTitle: "Spark Tracker",
    projectSparkTrackerDescription: "Täiustatud eluloendur Magic: The Gatheringu jaoks mitmikmängija toega, üksikasjaliku statistika ja täieliku kohandamisega.",
    projectSparkTrackerFeature1: "Eluloendur kuni 6 mängijale",
    projectSparkTrackerFeature2: "Komandöri kahjustuse jälgimine",
    projectSparkTrackerFeature3: "Loendurite ja mürgituse jälgimine",
    projectSparkTrackerFeature4: "Kohandatavad teemad ja tume režiim",
    projectSparkTrackerFeature5: "iPadi tugi optimeeritud liidesega",
    projectCookbookProTitle: "Cookbook Pro",
    projectCookbookProDescription: "Täielik platvorm kulinaarsete retseptide avastamiseks, korraldamiseks ja jagamiseks nutika toidukorra planeerimisega.",
    projectCookbookProFeature1: "Retseptide kogu täiustatud otsinguga",
    projectCookbookProFeature2: "Nädala toidukorra planeerija",
    projectCookbookProFeature3: "Automaatne ostunimekiri",
    projectCookbookProFeature4: "Lemmikrtseptide jagamine",
    projectCookbookProFeature5: "Integreeritud toitumiskalkulaator",
    projectCookbookProFeature6: "Apple Watchi integratsioon",
    // Project media translations
    viewDemo: "Vaata demot",
    watchVideo: "Vaata videot",
    liveDemo: "Reaalajas demo",
    viewScreenshots: "Vaata ekraanipilte",
    projectGallery: "Projekti galerii",
    demoPreview: "Demo eelvaade",
    fullDemo: "Täielik demo",
    openInNewTab: "Ava uues sakis",
    viewOnGithub: "Vaata GitHubis",
    techStack: "Tehnoloogia virn",
    projectDetails: "Projekti üksikasjad",
    closeModal: "Sulge",
    nextImage: "Järgmine pilt",
    previousImage: "Eelmine pilt",
    imageOf: "Pilt {current} / {total}",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
